settings:
  clusterName: "ndomiv1-management"
  
controller:
  containerName: controller
  image:
    repository: ghcr.io/absaoss/karpenter-provider-vsphere
    tag: latest # x-release-please-version

  envFrom:
    - secretRef:
        name: vsphere-credentials

  env:
    - name: GOVC_URL
      value: "vc-vx-sdc.caas.absa.co.za"
    - name: VSPHERE_PATH
      value: "karpenter"
    - name: GOVC_INSECURE
      value: "true"