apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vsphere-credentials
  namespace: ndomiv1
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: vcenter
      metadataPolicy: None
      property: vcenter_user
    secretKey: GOVC_USERNAME
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: vcenter
      metadataPolicy: None
      property: vcenter_password
    secretKey: GOVC_PASSWORD
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend